version: '3.8'
services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: document_delivery
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/document_delivery"
      NEXTAUTH_SECRET: "your_super_secret_key"
      NEXTAUTH_URL: "http://localhost:3000"
    depends_on:
      - db
volumes:
  db_data:
